package meineregeln.rules

import org.richard.buero.Item;
import org.richard.buero.Item.Category;
import org.richard.buero.Order;
import org.richard.buero.Customer;


rule "Classify Item - Low Range"
    when
        $i: Item(cost < 200)
    then
        $i.setCategory(Category.LOW_RANGE);
end

rule "classify customer by order size"
    when
        $o: Order(orderLines.size >= 5, $customer: customer)
        and
        $c: Customer(this == $customer, category == Customer.Category.NA)

    then
        ;
        modify($c){
            setCategory(Customer.Category.SILVER)
        };
end